# docker-compose.yml
# services and containers to be rune images
services:
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - 4000:5173
    env_file:
      - ./server/.env.development
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync
  
  redis:
    image: redis:alpine
    # container_name: redis
    ports:
      - '6379:6379'
          
  api:
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build: ./server
    ports:
      - 8080:8080
    env_file:
      - ./server/.env.development
    # volumes:
      # - ./server:/app
      # - /app/node_modules
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    # volumes:
      # - hello:/data/db
# volumes:
  # hello:
